---
- name: "Apache instalation using docker"
  hosts: prod

  become: true
  pre_tasks:
    - name: Install some package
      package: name='{{ item }}' state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - wget
        - git
    - name: Install python-pip 
      yum: name=python-pip state=present update_cache=yes
    - name: Install docker python
      pip: name=docker-py
  tasks:
    - name: Copy website template
      template:
        src: index.html.j2
        dest: /home/admin/index.html.j2
    - name: Create a data container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80" 
        volumes:
          - /home/admin/index.html: /usr/local/apache2/htdocs/index.html
             
